In [1]:
import numpy as np

In [2]:
# valid sudoku check

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
np.sum(s,axis= 1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n)


[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [6]:
# -----------genneral questions----------

In [12]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [24]:
#Get the shape of the matrix.
np.shape(data)
#Find the average age of students.
np.mean(data[:,0:1])
#Extract Math marks of all students.
data[:,1:2]
#Find the highest Science mark.
sc = data[:,2:3]
sc.max()
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]
#Increase Math marks of all students by 5.
data[:,1]+= 5
data
#Find how many students are younger than 19.
len(data[data[:,0] < 19])
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:] , axis = 0)
#Get data of students who scored at least 80 in both subjects.
data[(data[ :,1]>80) & (data[:,2] >80)]
#Replace all Science marks < 75 with 0.
data[:,2]data[:,2] < 75 = 0
data

SyntaxError: invalid syntax (3016996164.py, line 22)