In [2]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
# indexing
arr[9]

np.int64(20)

In [5]:
# slicing
arr[1:5]
# arr[:5] default start value is 0 and end value is last index
# start:end+1
arr_slice = arr[1:7:2]
arr_slice

array([12, 14, 16])

In [6]:
# matrix
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [7]:
arr[0,1]
# row,column

np.int64(2)

In [8]:
arr[0:2,1:3]

array([[2, 3],
       [8, 9]])

In [9]:
# bool indexing
arr = np.arange(11,21)
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr[bool_inde]