In [3]:
import numpy as np

In [4]:
arr = np.array(([1,2,3,4]))

In [5]:
print(arr)

[1 2 3 4]


In [6]:
a = [1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [7]:
# array generation functions

In [8]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [12]:
arr = np.linspace(0,10,10)
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
# random generation functiona

In [14]:
np.random.rand(10)
# for genrating between 0 and 1

array([0.35291964, 0.22136151, 0.69526048, 0.40475144, 0.92428854,
       0.96016869, 0.31144043, 0.76999678, 0.33858981, 0.25812477])

In [15]:
np.random.randn(10) 
# for geberation between -3 and 3 (standardization)

array([-0.31331601, -0.74728778,  0.40879473,  0.28631707, -0.89637954,
       -0.14336331,  0.60501956, -0.02137222,  0.57239796,  0.41485721])

In [16]:
np.random.randint(10,20,10)

array([10, 19, 19, 11, 12, 12, 13, 13, 15, 11])

In [17]:
# array attributes

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
# array methods

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

np.int64(1)

In [27]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [28]:
arr.mean()

np.float64(5.0)

In [29]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()
# index of max element

np.int64(8)

In [32]:
# resizing and reshaping

In [37]:
arr = np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
# reshaping
arr = arr.reshape(5,6)